"""add_indicator_versioning

Revision ID: 04567af303c9
Revises: 7cbba7e09fb4
Create Date: 2025-11-06 13:16:41.678674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "04567af303c9"
down_revision: Union[str, Sequence[str], None] = "7cbba7e09fb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adds versioning support to indicators:
    - Creates indicators_history table for archival
    - Adds version, is_active, is_auto_calculable, is_profiling_only columns
    - Adds calculation_schema, remark_schema, technical_notes_text columns
    - Makes form_schema nullable
    - Sets default values for existing indicators
    """
    # Create indicators_history table
    op.create_table(
        "indicators_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("indicator_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_auto_calculable", sa.Boolean(), nullable=False),
        sa.Column("is_profiling_only", sa.Boolean(), nullable=False),
        sa.Column("form_schema", sa.JSON(), nullable=True),
        sa.Column("calculation_schema", sa.JSON(), nullable=True),
        sa.Column("remark_schema", sa.JSON(), nullable=True),
        sa.Column("technical_notes_text", sa.String(), nullable=True),
        sa.Column("governance_area_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=False),
        sa.Column("archived_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["archived_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("indicator_id", "version", name="uq_indicator_version"),
    )
    op.create_index(op.f("ix_indicators_history_id"), "indicators_history", ["id"], unique=False)
    op.create_index(
        op.f("ix_indicators_history_indicator_id"),
        "indicators_history",
        ["indicator_id"],
        unique=False,
    )

    # Add new columns to indicators table with server defaults for existing rows
    op.add_column(
        "indicators",
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
    )
    op.add_column(
        "indicators",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.add_column(
        "indicators",
        sa.Column("is_auto_calculable", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "indicators",
        sa.Column("is_profiling_only", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column("indicators", sa.Column("calculation_schema", sa.JSON(), nullable=True))
    op.add_column("indicators", sa.Column("remark_schema", sa.JSON(), nullable=True))
    op.add_column("indicators", sa.Column("technical_notes_text", sa.String(), nullable=True))

    # Make form_schema nullable to support migration
    op.alter_column(
        "indicators",
        "form_schema",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )

    # Remove server defaults after migration (we want defaults in Python code, not DB)
    op.alter_column("indicators", "version", server_default=None)
    op.alter_column("indicators", "is_active", server_default=None)
    op.alter_column("indicators", "is_auto_calculable", server_default=None)
    op.alter_column("indicators", "is_profiling_only", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indicators",
        "form_schema",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_column("indicators", "technical_notes_text")
    op.drop_column("indicators", "remark_schema")
    op.drop_column("indicators", "calculation_schema")
    op.drop_column("indicators", "is_profiling_only")
    op.drop_column("indicators", "is_auto_calculable")
    op.drop_column("indicators", "is_active")
    op.drop_column("indicators", "version")
    op.drop_index(op.f("ix_indicators_history_indicator_id"), table_name="indicators_history")
    op.drop_index(op.f("ix_indicators_history_id"), table_name="indicators_history")
    op.drop_table("indicators_history")
    # ### end Alembic commands ###
