"""add created_at and updated_at to indicators

Revision ID: 268626414026
Revises: 64a5bb7d4b4d
Create Date: 2025-11-06 18:19:01.477760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268626414026'
down_revision: Union[str, Sequence[str], None] = '64a5bb7d4b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first, then set default values for existing rows
    op.add_column('indicators', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('indicators', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('indicators_history', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('indicators_history', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Update existing rows with current timestamp
    op.execute("UPDATE indicators SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE indicators_history SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")

    # Now make the columns non-nullable
    op.alter_column('indicators', 'created_at', nullable=False)
    op.alter_column('indicators', 'updated_at', nullable=False)
    op.alter_column('indicators_history', 'created_at', nullable=False)
    op.alter_column('indicators_history', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators_history', 'updated_at')
    op.drop_column('indicators_history', 'created_at')
    op.drop_column('indicators', 'updated_at')
    op.drop_column('indicators', 'created_at')
    # ### end Alembic commands ###
