"""add generated_remark column to assessment_responses

Revision ID: 996bae672415
Revises: 268626414026
Create Date: 2025-11-06 21:52:29.245164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996bae672415'
down_revision: Union[str, Sequence[str], None] = '268626414026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_responses', sa.Column('generated_remark', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_responses', 'generated_remark')
    # ### end Alembic commands ###
