"""create_assessment_cycles_and_deadline_overrides_tables

Revision ID: c0ef832297f3
Revises: fb588c0746a9
Create Date: 2025-11-07 00:24:33.167014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0ef832297f3"
down_revision: Union[str, Sequence[str], None] = "fb588c0746a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_cycles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("phase1_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rework_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("phase2_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calibration_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assessment_cycles_id"), "assessment_cycles", ["id"], unique=False)
    op.create_index(
        op.f("ix_assessment_cycles_is_active"),
        "assessment_cycles",
        ["is_active"],
        unique=False,
    )
    op.create_index(op.f("ix_assessment_cycles_year"), "assessment_cycles", ["year"], unique=False)
    op.create_index(
        "ix_assessment_cycles_year_desc",
        "assessment_cycles",
        [sa.literal_column("year DESC")],
        unique=False,
    )
    op.create_index(
        "uq_assessment_cycles_single_active",
        "assessment_cycles",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_table(
        "deadline_overrides",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("barangay_id", sa.Integer(), nullable=False),
        sa.Column("indicator_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("original_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("new_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["barangay_id"],
            ["barangays.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["assessment_cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deadline_overrides_barangay_id"),
        "deadline_overrides",
        ["barangay_id"],
        unique=False,
    )
    op.create_index(
        "ix_deadline_overrides_barangay_indicator",
        "deadline_overrides",
        ["barangay_id", "indicator_id"],
        unique=False,
    )
    op.create_index(
        "ix_deadline_overrides_created_at_desc",
        "deadline_overrides",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadline_overrides_created_by"),
        "deadline_overrides",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        "ix_deadline_overrides_cycle_barangay",
        "deadline_overrides",
        ["cycle_id", "barangay_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadline_overrides_cycle_id"),
        "deadline_overrides",
        ["cycle_id"],
        unique=False,
    )
    op.create_index(op.f("ix_deadline_overrides_id"), "deadline_overrides", ["id"], unique=False)
    op.create_index(
        op.f("ix_deadline_overrides_indicator_id"),
        "deadline_overrides",
        ["indicator_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deadline_overrides_indicator_id"), table_name="deadline_overrides")
    op.drop_index(op.f("ix_deadline_overrides_id"), table_name="deadline_overrides")
    op.drop_index(op.f("ix_deadline_overrides_cycle_id"), table_name="deadline_overrides")
    op.drop_index("ix_deadline_overrides_cycle_barangay", table_name="deadline_overrides")
    op.drop_index(op.f("ix_deadline_overrides_created_by"), table_name="deadline_overrides")
    op.drop_index("ix_deadline_overrides_created_at_desc", table_name="deadline_overrides")
    op.drop_index("ix_deadline_overrides_barangay_indicator", table_name="deadline_overrides")
    op.drop_index(op.f("ix_deadline_overrides_barangay_id"), table_name="deadline_overrides")
    op.drop_table("deadline_overrides")
    op.drop_index(
        "uq_assessment_cycles_single_active",
        table_name="assessment_cycles",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index("ix_assessment_cycles_year_desc", table_name="assessment_cycles")
    op.drop_index(op.f("ix_assessment_cycles_year"), table_name="assessment_cycles")
    op.drop_index(op.f("ix_assessment_cycles_is_active"), table_name="assessment_cycles")
    op.drop_index(op.f("ix_assessment_cycles_id"), table_name="assessment_cycles")
    op.drop_table("assessment_cycles")
    # ### end Alembic commands ###
