"""create_bbi_tables

Revision ID: fb588c0746a9
Revises: 996bae672415
Create Date: 2025-11-06 22:54:42.676767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb588c0746a9"
down_revision: Union[str, Sequence[str], None] = "996bae672415"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bbis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("mapping_rules", sa.JSON(), nullable=True),
        sa.Column("governance_area_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["governance_area_id"],
            ["governance_areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bbis_governance_area_id"), "bbis", ["governance_area_id"], unique=False
    )
    op.create_index(op.f("ix_bbis_id"), "bbis", ["id"], unique=False)
    op.create_table(
        "bbi_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "FUNCTIONAL",
                "NON_FUNCTIONAL",
                name="bbi_status_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("calculation_details", sa.JSON(), nullable=True),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("bbi_id", sa.Integer(), nullable=False),
        sa.Column("calculation_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bbi_id"],
            ["bbis.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bbi_results_assessment_id"),
        "bbi_results",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(op.f("ix_bbi_results_bbi_id"), "bbi_results", ["bbi_id"], unique=False)
    op.create_index(op.f("ix_bbi_results_id"), "bbi_results", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bbi_results_id"), table_name="bbi_results")
    op.drop_index(op.f("ix_bbi_results_bbi_id"), table_name="bbi_results")
    op.drop_index(op.f("ix_bbi_results_assessment_id"), table_name="bbi_results")
    op.drop_table("bbi_results")
    op.drop_index(op.f("ix_bbis_id"), table_name="bbis")
    op.drop_index(op.f("ix_bbis_governance_area_id"), table_name="bbis")
    op.drop_table("bbis")
    # ### end Alembic commands ###
