# 📋 Schemas Package
# Pydantic schemas for API data validation

# 📝 Schema Exports
# Central location for importing all Pydantic schemas

from .assessment import (
    MOV,
    Assessment,
    AssessmentCreate,
    AssessmentListResponse,
    AssessmentResponse,
    AssessmentResponseCreate,
    AssessmentResponseListResponse,
    AssessmentResponseUpdate,
    AssessmentResponseWithDetails,
    AssessmentSubmissionValidation,
    AssessmentUpdate,
    AssessmentWithIndicators,
    AssessmentWithResponses,
    CalibrationSummaryResponse,
    FeedbackComment,
    FeedbackCommentCreate,
    FeedbackCommentListResponse,
    FeedbackCommentUpdate,
    FormSchemaValidation,
    GovernanceAreaWithIndicators,
    Indicator,
    IndicatorSummary,
    IndicatorWithResponse,
    MOVCreate,
    MOVListResponse,
    MOVUpdate,
    ReworkSummaryResponse,
)
from .analytics import (
    AreaBreakdown,
    ComplianceRate,
    DashboardKPIResponse,
    FailedIndicator,
    ReworkStats,
    StatusDistributionItem,
    TrendData,
)
from .assessor import (
    AnnotationCreate,
    AnnotationResponse,
    AnnotationUpdate,
    AssessorAnalyticsResponse,
    AssessmentDetailsResponse,
    AssessorQueueItem,
    MOVUploadResponse,
    PdfRect,
    PerformanceOverview,
    SystemicWeakness,
    ValidationRequest,
    ValidationResponse,
    WorkflowMetrics,
)
from .blgu_dashboard import (
    BLGUDashboardResponse,
    GovernanceAreaGroup,
    IndicatorItem,
    IndicatorNavigationItem,
    ReworkComment,
)
from .system import ApiResponse, ErrorResponse, HealthCheck, SuccessResponse
from .token import AuthToken, LoginRequest, Token, TokenPayload
from .user import User, UserCreate, UserInDB, UserUpdate

__all__ = [
    # Analytics schemas
    "DashboardKPIResponse",
    "ComplianceRate",
    "AreaBreakdown",
    "FailedIndicator",
    "TrendData",
    "StatusDistributionItem",
    "ReworkStats",
    # Assessment schemas
    "Assessment",
    "AssessmentCreate",
    "AssessmentUpdate",
    "AssessmentWithResponses",
    "AssessmentResponse",
    "AssessmentResponseCreate",
    "AssessmentResponseUpdate",
    "AssessmentResponseWithDetails",
    "MOV",
    "MOVCreate",
    "MOVUpdate",
    "FeedbackComment",
    "FeedbackCommentCreate",
    "FeedbackCommentUpdate",
    "Indicator",
    "IndicatorSummary",
    "IndicatorWithResponse",
    "AssessmentWithIndicators",
    "GovernanceAreaWithIndicators",
    "AssessmentListResponse",
    "AssessmentResponseListResponse",
    "MOVListResponse",
    "FeedbackCommentListResponse",
    "AssessmentSubmissionValidation",
    "FormSchemaValidation",
    "ReworkSummaryResponse",
    "CalibrationSummaryResponse",
    # User schemas
    "User",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    # Token schemas
    "LoginRequest",
    "AuthToken",
    "Token",
    "TokenPayload",
    # System schemas
    "ApiResponse",
    "HealthCheck",
    "ErrorResponse",
    "SuccessResponse",
    # Assessor schemas
    "AssessorQueueItem",
    "AssessmentDetailsResponse",
    "ValidationRequest",
    "ValidationResponse",
    "MOVUploadResponse",
    "AssessorAnalyticsResponse",
    "PerformanceOverview",
    "SystemicWeakness",
    "WorkflowMetrics",
    "AnnotationCreate",
    "AnnotationResponse",
    "AnnotationUpdate",
    "PdfRect",
    # BLGU Dashboard schemas
    "BLGUDashboardResponse",
    "GovernanceAreaGroup",
    "IndicatorItem",
    "IndicatorNavigationItem",
    "ReworkComment",
]
