# 📋 Schemas Package
# Pydantic schemas for API data validation

# 📝 Schema Exports
# Central location for importing all Pydantic schemas

from .analytics import (
    AreaBreakdown,
    ComplianceRate,
    DashboardKPIResponse,
    FailedIndicator,
    ReworkStats,
    StatusDistributionItem,
    TrendData,
)
from .assessment import (
    MOV,
    Assessment,
    AssessmentCreate,
    AssessmentListResponse,
    AssessmentResponse,
    AssessmentResponseCreate,
    AssessmentResponseListResponse,
    AssessmentResponseUpdate,
    AssessmentResponseWithDetails,
    AssessmentSubmissionValidation,
    AssessmentUpdate,
    AssessmentWithIndicators,
    AssessmentWithResponses,
    CalibrationSummaryResponse,
    FeedbackComment,
    FeedbackCommentCreate,
    FeedbackCommentListResponse,
    FeedbackCommentUpdate,
    FormSchemaValidation,
    GovernanceAreaWithIndicators,
    Indicator,
    IndicatorSummary,
    IndicatorWithResponse,
    MOVCreate,
    MOVListResponse,
    MOVUpdate,
    ReworkSummaryResponse,
)
from .assessment_activity import (
    ActivityAction,
    ActivityByActionCount,
    ActivityCountsResponse,
    ActivitySummary,
    AssessmentActivityCreate,
    AssessmentActivityFilters,
    AssessmentActivityListResponse,
    AssessmentActivityResponse,
    AssessmentTimelineItem,
    AssessmentTimelineResponse,
)
from .assessment_year import (
    AccessibleYearsResponse,
    ActivateYearRequest,
    ActivateYearResponse,
    AssessmentYearBase,
    AssessmentYearCreate,
    AssessmentYearListResponse,
    AssessmentYearResponse,
    AssessmentYearSimple,
    AssessmentYearUpdate,
    PublishYearRequest,
    PublishYearResponse,
)
from .assessor import (
    AnnotationCreate,
    AnnotationResponse,
    AnnotationUpdate,
    AssessmentDetailsResponse,
    AssessorAnalyticsResponse,
    AssessorQueueItem,
    MOVUploadResponse,
    PdfRect,
    PerformanceOverview,
    ReviewHistoryDetail,
    ReviewHistoryFeedbackComment,
    ReviewHistoryIndicator,
    ReviewHistoryItem,
    ReviewHistoryResponse,
    SystemicWeakness,
    ValidationRequest,
    ValidationResponse,
    WorkflowMetrics,
)
from .blgu_dashboard import (
    BLGUDashboardResponse,
    GovernanceAreaGroup,
    IndicatorItem,
    IndicatorNavigationItem,
    ReworkComment,
)
from .municipal_export import (
    AnalyticsSummaryExport,
    AssessmentExportRow,
    AvailableCycle,
    ExportDataType,
    ExportGenerateResponse,
    ExportOptions,
    ExportOptionsResponse,
    ExportRequest,
    ExportSummary,
    GovernanceAreaExportRow,
    IndicatorExportRow,
    UserExportRow,
)
from .system import ApiResponse, ErrorResponse, HealthCheck, SuccessResponse
from .token import AuthToken, LoginRequest, Token, TokenPayload
from .user import User, UserCreate, UserInDB, UserUpdate

__all__ = [
    # Analytics schemas
    "DashboardKPIResponse",
    "ComplianceRate",
    "AreaBreakdown",
    "FailedIndicator",
    "TrendData",
    "StatusDistributionItem",
    "ReworkStats",
    # Assessment Year schemas
    "AssessmentYearBase",
    "AssessmentYearCreate",
    "AssessmentYearUpdate",
    "AssessmentYearResponse",
    "AssessmentYearListResponse",
    "AssessmentYearSimple",
    "ActivateYearRequest",
    "ActivateYearResponse",
    "PublishYearRequest",
    "PublishYearResponse",
    "AccessibleYearsResponse",
    # Assessment schemas
    "Assessment",
    "AssessmentCreate",
    "AssessmentUpdate",
    "AssessmentWithResponses",
    "AssessmentResponse",
    "AssessmentResponseCreate",
    "AssessmentResponseUpdate",
    "AssessmentResponseWithDetails",
    "MOV",
    "MOVCreate",
    "MOVUpdate",
    "FeedbackComment",
    "FeedbackCommentCreate",
    "FeedbackCommentUpdate",
    "Indicator",
    "IndicatorSummary",
    "IndicatorWithResponse",
    "AssessmentWithIndicators",
    "GovernanceAreaWithIndicators",
    "AssessmentListResponse",
    "AssessmentResponseListResponse",
    "MOVListResponse",
    "FeedbackCommentListResponse",
    "AssessmentSubmissionValidation",
    "FormSchemaValidation",
    "ReworkSummaryResponse",
    "CalibrationSummaryResponse",
    # User schemas
    "User",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    # Token schemas
    "LoginRequest",
    "AuthToken",
    "Token",
    "TokenPayload",
    # System schemas
    "ApiResponse",
    "HealthCheck",
    "ErrorResponse",
    "SuccessResponse",
    # Assessor schemas
    "AssessorQueueItem",
    "AssessmentDetailsResponse",
    "ValidationRequest",
    "ValidationResponse",
    "MOVUploadResponse",
    "AssessorAnalyticsResponse",
    "PerformanceOverview",
    "SystemicWeakness",
    "WorkflowMetrics",
    "AnnotationCreate",
    "AnnotationResponse",
    "AnnotationUpdate",
    "PdfRect",
    "ReviewHistoryResponse",
    "ReviewHistoryItem",
    "ReviewHistoryDetail",
    "ReviewHistoryIndicator",
    "ReviewHistoryFeedbackComment",
    # BLGU Dashboard schemas
    "BLGUDashboardResponse",
    "GovernanceAreaGroup",
    "IndicatorItem",
    "IndicatorNavigationItem",
    "ReworkComment",
    # Assessment Activity schemas
    "ActivityAction",
    "AssessmentActivityCreate",
    "AssessmentActivityResponse",
    "AssessmentActivityListResponse",
    "AssessmentActivityFilters",
    "AssessmentTimelineItem",
    "AssessmentTimelineResponse",
    "ActivitySummary",
    "ActivityByActionCount",
    "ActivityCountsResponse",
    # Municipal Export schemas
    "ExportOptions",
    "ExportRequest",
    "ExportDataType",
    "AvailableCycle",
    "ExportOptionsResponse",
    "ExportSummary",
    "ExportGenerateResponse",
    "AssessmentExportRow",
    "UserExportRow",
    "GovernanceAreaExportRow",
    "IndicatorExportRow",
    "AnalyticsSummaryExport",
]
