# 📊 Analytics Schemas
# Pydantic models for analytics and dashboard-related API requests and responses

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

# ============================================================================
# Dashboard KPI Schemas
# ============================================================================


class ComplianceRate(BaseModel):
    """Overall compliance rate statistics."""

    model_config = ConfigDict(from_attributes=True)

    total_barangays: int = Field(..., description="Total number of barangays assessed")
    passed: int = Field(..., description="Number of barangays that passed")
    failed: int = Field(..., description="Number of barangays that failed")
    pass_percentage: float = Field(
        ..., description="Percentage of barangays that passed", ge=0, le=100
    )


class AreaBreakdown(BaseModel):
    """Compliance breakdown by governance area."""

    model_config = ConfigDict(from_attributes=True)

    area_code: str = Field(..., description="Governance area code")
    area_name: str = Field(..., description="Governance area name")
    passed: int = Field(..., description="Number of barangays that passed this area")
    failed: int = Field(..., description="Number of barangays that failed this area")
    percentage: float = Field(..., description="Pass percentage for this area", ge=0, le=100)


class FailedIndicator(BaseModel):
    """Indicator with high failure rate."""

    model_config = ConfigDict(from_attributes=True)

    indicator_id: int = Field(..., description="Unique identifier for the indicator")
    indicator_name: str = Field(..., description="Name of the indicator")
    indicator_code: str | None = Field(None, description="Indicator code (e.g., '1.1.1')")
    governance_area: str | None = Field(None, description="Governance area name")
    failure_count: int = Field(..., description="Number of times this indicator failed")
    percentage: float = Field(
        ..., description="Failure rate as percentage of total barangays", ge=0, le=100
    )


class TrendData(BaseModel):
    """Historical trend data for a cycle."""

    model_config = ConfigDict(from_attributes=True)

    cycle_id: int = Field(..., description="Assessment cycle identifier")
    cycle_name: str = Field(..., description="Name of the assessment cycle")
    pass_rate: float = Field(..., description="Pass rate for this cycle", ge=0, le=100)
    date: datetime = Field(..., description="Date of the cycle")


class StatusDistributionItem(BaseModel):
    """Single status distribution item for the workflow funnel."""

    model_config = ConfigDict(from_attributes=True)

    status: str = Field(..., description="Assessment status name")
    count: int = Field(..., description="Number of assessments in this status", ge=0)
    percentage: float = Field(..., description="Percentage of total assessments", ge=0, le=100)


class ReworkStats(BaseModel):
    """Rework and calibration statistics."""

    model_config = ConfigDict(from_attributes=True)

    total_assessments: int = Field(..., description="Total number of assessments")
    assessments_with_rework: int = Field(..., description="Assessments that used rework cycle")
    rework_rate: float = Field(
        ..., description="Percentage of assessments that needed rework", ge=0, le=100
    )
    assessments_with_calibration: int = Field(..., description="Assessments that used calibration")
    calibration_rate: float = Field(
        ...,
        description="Percentage of assessments that needed calibration",
        ge=0,
        le=100,
    )


class TopReworkReason(BaseModel):
    """A single top reason for rework or calibration (AI-generated or aggregated)."""

    model_config = ConfigDict(from_attributes=True)

    reason: str = Field(..., description="The reason description")
    count: int = Field(..., description="Number of occurrences across assessments", ge=0)
    source: Literal["rework", "calibration"] = Field(
        ...,
        description="Source of the reason: 'rework' or 'calibration'",
    )
    governance_area: str | None = Field(None, description="Related governance area if applicable")


class TopReworkReasons(BaseModel):
    """Top reasons for rework/calibration across all assessments (AI-analyzed)."""

    model_config = ConfigDict(from_attributes=True)

    reasons: list[TopReworkReason] = Field(
        default_factory=list,
        description="List of top reasons for rework/calibration",
        max_length=10,
    )
    total_rework_assessments: int = Field(
        ..., description="Total assessments that had rework", ge=0
    )
    total_calibration_assessments: int = Field(
        ..., description="Total assessments that had calibration", ge=0
    )
    generated_by_ai: bool = Field(True, description="Whether the reasons were generated by AI")


# ============================================================================
# BBI Analytics Schemas (DILG MC 2024-417)
# ============================================================================


class BBIAnalyticsItem(BaseModel):
    """BBI compliance analytics for a single BBI type."""

    model_config = ConfigDict(from_attributes=True)

    bbi_id: int = Field(..., description="Unique identifier for the BBI")
    bbi_name: str = Field(..., description="Full name of the BBI")
    bbi_abbreviation: str = Field(..., description="BBI abbreviation (e.g., BDC, BDRRMC)")
    average_compliance: float = Field(
        ...,
        description="Average compliance percentage across all barangays",
        ge=0,
        le=100,
    )
    highly_functional_count: int = Field(
        ..., description="Number of barangays with 75%+ compliance", ge=0
    )
    moderately_functional_count: int = Field(
        ..., description="Number of barangays with 50-74% compliance", ge=0
    )
    low_functional_count: int = Field(
        ..., description="Number of barangays with <50% compliance", ge=0
    )
    total_barangays: int = Field(..., description="Total barangays assessed for this BBI", ge=0)


class BBIAnalyticsSummary(BaseModel):
    """Summary statistics for all BBI analytics."""

    model_config = ConfigDict(from_attributes=True)

    total_assessments: int = Field(..., description="Total assessments with BBI results", ge=0)
    overall_average_compliance: float = Field(
        ..., description="Overall average compliance across all BBIs", ge=0, le=100
    )
    total_highly_functional: int = Field(..., description="Total highly functional ratings", ge=0)
    total_moderately_functional: int = Field(
        ..., description="Total moderately functional ratings", ge=0
    )
    total_low_functional: int = Field(..., description="Total low functional ratings", ge=0)


class BBIAnalyticsData(BaseModel):
    """Complete BBI analytics data for the dashboard."""

    model_config = ConfigDict(from_attributes=True)

    summary: BBIAnalyticsSummary = Field(..., description="Summary statistics for all BBIs")
    bbi_breakdown: list[BBIAnalyticsItem] = Field(
        default_factory=list, description="Per-BBI compliance breakdown"
    )


class BarangayRanking(BaseModel):
    """Barangay ranking by compliance score."""

    model_config = ConfigDict(from_attributes=True)

    barangay_id: int = Field(..., description="Unique identifier for the barangay")
    barangay_name: str = Field(..., description="Name of the barangay")
    score: float = Field(..., description="Compliance score for this barangay", ge=0, le=100)
    rank: int = Field(..., description="Ranking position (1 = highest score)", ge=1)


class DashboardKPIResponse(BaseModel):
    """Complete dashboard KPI response containing all metrics."""

    model_config = ConfigDict(from_attributes=True)

    overall_compliance_rate: ComplianceRate = Field(..., description="Overall pass/fail statistics")
    completion_status: ComplianceRate = Field(..., description="Completion status of assessments")
    area_breakdown: list[AreaBreakdown] = Field(
        default_factory=list, description="Compliance breakdown by governance area"
    )
    top_failed_indicators: list[FailedIndicator] = Field(
        default_factory=list,
        description="Top 5 most frequently failed indicators",
        max_length=5,
    )
    trends: list[TrendData] = Field(
        default_factory=list,
        description="Historical trend data across cycles",
        max_length=3,
    )
    barangay_rankings: list[BarangayRanking] = Field(
        default_factory=list, description="Barangays ranked by compliance score"
    )
    status_distribution: list[StatusDistributionItem] = Field(
        default_factory=list,
        description="Distribution of assessments by workflow status",
    )
    rework_stats: ReworkStats = Field(..., description="Rework and calibration usage statistics")
    top_rework_reasons: TopReworkReasons | None = Field(
        None, description="Top AI-generated reasons for rework/calibration"
    )
    bbi_analytics: BBIAnalyticsData | None = Field(
        None, description="BBI compliance analytics per DILG MC 2024-417"
    )
    total_barangays: int = Field(..., description="Total number of barangays in the municipality")


class RefreshAnalysisResponse(BaseModel):
    """Response for dashboard analysis refresh operation."""

    model_config = ConfigDict(from_attributes=True)

    message: str = Field(..., description="Status message")
    cache_invalidated: bool = Field(
        ..., description="Whether the cache was successfully invalidated"
    )
    top_rework_reasons: TopReworkReasons | None = Field(
        None, description="Refreshed top rework/calibration reasons"
    )


# ============================================================================
# Reports Page Schemas
# ============================================================================


class BarChartData(BaseModel):
    """Bar chart data for pass/fail rates by governance area."""

    model_config = ConfigDict(from_attributes=True)

    area_code: str = Field(..., description="Governance area code")
    area_name: str = Field(..., description="Governance area name")
    passed: int = Field(..., description="Number of barangays that passed")
    failed: int = Field(..., description="Number of barangays that failed")
    pass_percentage: float = Field(..., description="Pass rate percentage", ge=0, le=100)


class PieChartData(BaseModel):
    """Pie chart data for overall compliance status distribution."""

    model_config = ConfigDict(from_attributes=True)

    status: str = Field(..., description="Status label (Pass/Fail/In Progress)")
    count: int = Field(..., description="Number of barangays in this status", ge=0)
    percentage: float = Field(..., description="Percentage of total", ge=0, le=100)


class ChartData(BaseModel):
    """Container for all chart visualizations."""

    model_config = ConfigDict(from_attributes=True)

    bar_chart: list[BarChartData] = Field(
        default_factory=list,
        description="Bar chart data showing pass/fail rates by governance area",
    )
    pie_chart: list[PieChartData] = Field(
        default_factory=list,
        description="Pie chart data showing overall status distribution",
    )
    line_chart: list[TrendData] = Field(
        default_factory=list, description="Line chart data showing trends over cycles"
    )


class BarangayMapPoint(BaseModel):
    """Geographic data point for a barangay on the map."""

    model_config = ConfigDict(from_attributes=True)

    barangay_id: int = Field(..., description="Unique identifier for the barangay")
    name: str = Field(..., description="Barangay name")
    lat: float | None = Field(None, description="Latitude coordinate")
    lng: float | None = Field(None, description="Longitude coordinate")
    status: str = Field(..., description="Compliance status (Pass/Fail/In Progress)")
    score: float | None = Field(None, description="Compliance score", ge=0, le=100)


class MapData(BaseModel):
    """Geographic map data for barangays."""

    model_config = ConfigDict(from_attributes=True)

    barangays: list[BarangayMapPoint] = Field(
        default_factory=list,
        description="List of barangays with geographic coordinates and status",
    )


class AssessmentRow(BaseModel):
    """Single row in the assessment data table."""

    model_config = ConfigDict(from_attributes=True)

    barangay_id: int = Field(..., description="Unique identifier for the barangay")
    barangay_name: str = Field(..., description="Name of the barangay")
    governance_area: str = Field(..., description="Governance area code")
    status: str = Field(..., description="Assessment status (Pass/Fail/In Progress)")
    score: float | None = Field(None, description="Compliance score", ge=0, le=100)
    governance_areas_passed: int | None = Field(
        None, description="Number of governance areas passed"
    )
    total_governance_areas: int | None = Field(None, description="Total number of governance areas")
    indicators_passed: int | None = Field(
        None, description="Number of indicators passed (Pass/Conditional)"
    )
    total_indicators: int | None = Field(None, description="Total number of indicators")


class TableData(BaseModel):
    """Paginated table data for assessments."""

    model_config = ConfigDict(from_attributes=True)

    rows: list[AssessmentRow] = Field(
        default_factory=list, description="List of assessment rows for the current page"
    )
    total_count: int = Field(..., description="Total number of assessments matching filters", ge=0)
    page: int = Field(..., description="Current page number", ge=1)
    page_size: int = Field(..., description="Number of rows per page", ge=1, le=100)


class ReportMetadata(BaseModel):
    """Metadata about the generated report."""

    model_config = ConfigDict(from_attributes=True)

    generated_at: datetime = Field(..., description="Timestamp when the report was generated")
    assessment_year: int | None = Field(
        None, description="Filter: Assessment year (e.g., 2024, 2025)"
    )
    start_date: datetime | None = Field(None, description="Filter: Start date")
    end_date: datetime | None = Field(None, description="Filter: End date")
    governance_areas: list[str] | None = Field(None, description="Filter: Governance area codes")
    barangay_ids: list[int] | None = Field(None, description="Filter: Barangay IDs")
    status: str | None = Field(None, description="Filter: Status filter")


class ReportsDataResponse(BaseModel):
    """Complete reports page response with all visualizations and data."""

    model_config = ConfigDict(from_attributes=True)

    chart_data: ChartData = Field(..., description="Data for bar, pie, and line charts")
    map_data: MapData = Field(..., description="Geographic map data for barangays")
    table_data: TableData = Field(..., description="Paginated table data for assessments")
    metadata: ReportMetadata = Field(
        ..., description="Report generation metadata and applied filters"
    )
