# Composite action for setting up Python backend environment
# Reduces duplication across CI workflows
name: Setup Python API
description: Sets up Python 3.13 with uv and installs API dependencies

runs:
  using: composite
  steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      shell: bash
      run: pip install uv

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('apps/api/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies
      shell: bash
      run: cd apps/api && uv sync --group dev
