#!/usr/bin/env bash
#
# Development Startup Script for SINAG Worktrees
# Automatically detects worktree ports and starts services with correct configuration
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Get the directory of this script and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Default ports (for main worktree)
DEFAULT_API_PORT=8000
DEFAULT_WEB_PORT=3000

# Read ports from .worktree-info if it exists
get_worktree_ports() {
    local info_file="${PROJECT_ROOT}/.worktree-info"

    if [[ -f "$info_file" ]]; then
        export API_PORT=$(grep "API_PORT=" "$info_file" | cut -d'=' -f2)
        export WEB_PORT=$(grep "WEB_PORT=" "$info_file" | cut -d'=' -f2)
        export WORKTREE_NAME=$(grep "WORKTREE_NAME=" "$info_file" | cut -d'=' -f2)
    else
        export API_PORT=$DEFAULT_API_PORT
        export WEB_PORT=$DEFAULT_WEB_PORT
        export WORKTREE_NAME="main"
    fi
    return 0
}

# Print worktree info banner
print_banner() {
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  SINAG Development Server${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    if [[ "$WORKTREE_NAME" == "main" ]]; then
        echo -e "  Worktree:  ${GREEN}main (primary)${NC}"
    else
        echo -e "  Worktree:  ${YELLOW}${WORKTREE_NAME}${NC}"
    fi

    echo -e "  API Port:  ${BLUE}http://localhost:${API_PORT}${NC}"
    echo -e "  Web Port:  ${BLUE}http://localhost:${WEB_PORT}${NC}"
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

# Update .env.local with correct API URL for this worktree
# Preserves all existing non-API environment variables
update_web_env() {
    local env_file="${PROJECT_ROOT}/apps/web/.env.local"
    local temp_file=$(mktemp)

    # Write header and API URLs
    cat > "$temp_file" << EOF
# Auto-generated by dev-worktree.sh
# Worktree: ${WORKTREE_NAME}
# Generated: $(date -Iseconds)

NEXT_PUBLIC_API_URL=http://localhost:${API_PORT}
NEXT_PUBLIC_API_V1_URL=http://localhost:${API_PORT}/api/v1
EOF

    # Preserve all non-API settings from existing .env.local
    if [[ -f "$env_file" ]]; then
        # Extract non-API, non-comment, non-empty lines from existing file
        grep -v "^NEXT_PUBLIC_API" "$env_file" 2>/dev/null | grep -v "^#" | grep -v "^$" >> "$temp_file" || true
    fi

    mv "$temp_file" "$env_file"
}

# Start Redis if not running
# Handles both main repo (redis-celery, redis-cache) and worktree (redis) configurations
ensure_redis() {
    # Check which docker-compose configuration we have
    if grep -q "redis-celery:" "${PROJECT_ROOT}/docker-compose.yml" 2>/dev/null; then
        # Main repo: uses redis-celery and redis-cache services
        local need_start=false
        if ! docker ps --format '{{.Names}}' | grep -q "sinag-redis-celery"; then
            need_start=true
        fi
        if ! docker ps --format '{{.Names}}' | grep -q "sinag-redis-cache"; then
            need_start=true
        fi

        if $need_start; then
            echo -e "${BLUE}Starting Redis (celery + cache)...${NC}"
            docker compose -f "${PROJECT_ROOT}/docker-compose.yml" up -d redis-celery redis-cache
            echo -e "${GREEN}✓ Redis started${NC}"
        else
            echo -e "${GREEN}✓ Redis already running${NC}"
        fi
    else
        # Worktree: uses simplified single redis service
        if ! docker ps --format '{{.Names}}' | grep -q "sinag-redis"; then
            echo -e "${BLUE}Starting Redis...${NC}"
            docker compose -f "${PROJECT_ROOT}/docker-compose.yml" up -d redis
            echo -e "${GREEN}✓ Redis started${NC}"
        else
            echo -e "${GREEN}✓ Redis already running${NC}"
        fi
    fi
}

# Start all services
start_all() {
    get_worktree_ports
    print_banner

    # Ensure Redis is running
    ensure_redis

    # Update web .env.local with correct API URL
    update_web_env

    echo -e "${BLUE}Starting services...${NC}"
    echo ""

    cd "$PROJECT_ROOT"

    # Use concurrently to run all services with correct ports
    # Export ports for subprocesses
    export API_PORT WEB_PORT

    pnpm exec concurrently \
        -n "API,WEB,CELERY" \
        -c "blue,green,yellow" \
        "cd apps/api && uv run uvicorn main:app --reload --host 0.0.0.0 --port ${API_PORT}" \
        "cd apps/web && PORT=${WEB_PORT} pnpm exec next dev --turbopack" \
        "cd apps/api && uv run celery -A app.core.celery_app worker --loglevel=info --queues=notifications,classification"
}

# Start API only
start_api() {
    get_worktree_ports
    print_banner
    ensure_redis

    echo -e "${BLUE}Starting API on port ${API_PORT}...${NC}"
    cd "${PROJECT_ROOT}/apps/api"
    uv run uvicorn main:app --reload --host 0.0.0.0 --port "${API_PORT}"
}

# Start Web only
start_web() {
    get_worktree_ports
    print_banner
    update_web_env

    echo -e "${BLUE}Starting Web on port ${WEB_PORT}...${NC}"
    cd "${PROJECT_ROOT}/apps/web"
    PORT="${WEB_PORT}" pnpm exec next dev --turbopack
}

# Start without Celery
start_no_celery() {
    get_worktree_ports
    print_banner
    ensure_redis
    update_web_env

    echo -e "${BLUE}Starting API and Web (no Celery)...${NC}"
    echo ""

    cd "$PROJECT_ROOT"

    pnpm exec concurrently \
        -n "API,WEB" \
        -c "blue,green" \
        "cd apps/api && uv run uvicorn main:app --reload --host 0.0.0.0 --port ${API_PORT}" \
        "cd apps/web && PORT=${WEB_PORT} pnpm exec next dev --turbopack"
}

# Show current port configuration
show_ports() {
    get_worktree_ports

    echo -e "${CYAN}Port Configuration:${NC}"
    echo ""
    echo "  Worktree:  ${WORKTREE_NAME}"
    echo "  API Port:  ${API_PORT}"
    echo "  Web Port:  ${WEB_PORT}"
    echo ""

    if [[ -f "${PROJECT_ROOT}/.worktree-info" ]]; then
        echo -e "${BLUE}Source: .worktree-info${NC}"
    else
        echo -e "${YELLOW}Source: defaults (main worktree)${NC}"
    fi
}

# Usage
usage() {
    echo "SINAG Development Server for Worktrees"
    echo ""
    echo "Usage: $0 [command]"
    echo ""
    echo "Commands:"
    echo "  all, start    Start all services (API, Web, Celery) with worktree ports"
    echo "  api           Start API only with worktree port"
    echo "  web           Start Web only with worktree port"
    echo "  no-celery     Start API and Web without Celery"
    echo "  ports         Show current port configuration"
    echo "  help          Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0              # Start all services"
    echo "  $0 api          # Start API only"
    echo "  $0 ports        # Show port config"
    echo ""
}

# Main command handler
main() {
    local cmd="${1:-all}"

    case "$cmd" in
        all|start|"")
            start_all
            ;;
        api)
            start_api
            ;;
        web)
            start_web
            ;;
        no-celery|nc)
            start_no_celery
            ;;
        ports|port|p)
            show_ports
            ;;
        -h|--help|help)
            usage
            ;;
        *)
            echo -e "${RED}Unknown command: $cmd${NC}"
            echo ""
            usage
            exit 1
            ;;
    esac
}

main "$@"
