#!/usr/bin/env bash
#
# Production-like Test Script for SINAG
# Builds frontend first, then runs with production server for faster testing
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Get the directory of this script and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Default ports (for main worktree)
DEFAULT_API_PORT=8000
DEFAULT_WEB_PORT=3000

# Read ports from .worktree-info if it exists
get_worktree_ports() {
    local info_file="${PROJECT_ROOT}/.worktree-info"

    if [[ -f "$info_file" ]]; then
        export API_PORT=$(grep "API_PORT=" "$info_file" | cut -d'=' -f2)
        export WEB_PORT=$(grep "WEB_PORT=" "$info_file" | cut -d'=' -f2)
        export WORKTREE_NAME=$(grep "WORKTREE_NAME=" "$info_file" | cut -d'=' -f2)
    else
        export API_PORT=$DEFAULT_API_PORT
        export WEB_PORT=$DEFAULT_WEB_PORT
        export WORKTREE_NAME="main"
    fi
    return 0
}

# Print worktree info banner
print_banner() {
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  SINAG Production-like Test Server${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    if [[ "$WORKTREE_NAME" == "main" ]]; then
        echo -e "  Worktree:  ${GREEN}main (primary)${NC}"
    else
        echo -e "  Worktree:  ${YELLOW}${WORKTREE_NAME}${NC}"
    fi

    echo -e "  API Port:  ${BLUE}http://localhost:${API_PORT}${NC}"
    echo -e "  Web Port:  ${BLUE}http://localhost:${WEB_PORT}${NC}"
    echo -e "  Mode:      ${GREEN}Production build${NC}"
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

# Update .env.local with correct API URL for this worktree
update_web_env() {
    local env_file="${PROJECT_ROOT}/apps/web/.env.local"
    local temp_file=$(mktemp)

    cat > "$temp_file" << EOF
# Auto-generated by test-prod.sh
# Worktree: ${WORKTREE_NAME}
# Generated: $(date -Iseconds)

NEXT_PUBLIC_API_URL=http://localhost:${API_PORT}
NEXT_PUBLIC_API_V1_URL=http://localhost:${API_PORT}/api/v1
EOF

    if [[ -f "$env_file" ]]; then
        grep -v "^NEXT_PUBLIC_API" "$env_file" 2>/dev/null | grep -v "^#" | grep -v "^$" >> "$temp_file" || true
    fi

    mv "$temp_file" "$env_file"
}

# Start Redis if not running
ensure_redis() {
    if grep -q "redis-celery:" "${PROJECT_ROOT}/docker-compose.yml" 2>/dev/null; then
        local need_start=false
        if ! docker ps --format '{{.Names}}' | grep -q "sinag-redis-celery"; then
            need_start=true
        fi
        if ! docker ps --format '{{.Names}}' | grep -q "sinag-redis-cache"; then
            need_start=true
        fi

        if $need_start; then
            echo -e "${BLUE}Starting Redis (celery + cache)...${NC}"
            docker compose -f "${PROJECT_ROOT}/docker-compose.yml" up -d redis-celery redis-cache
            echo -e "${GREEN}✓ Redis started${NC}"
        else
            echo -e "${GREEN}✓ Redis already running${NC}"
        fi
    else
        if ! docker ps --format '{{.Names}}' | grep -q "sinag-redis"; then
            echo -e "${BLUE}Starting Redis...${NC}"
            docker compose -f "${PROJECT_ROOT}/docker-compose.yml" up -d redis
            echo -e "${GREEN}✓ Redis started${NC}"
        else
            echo -e "${GREEN}✓ Redis already running${NC}"
        fi
    fi
}

# Build frontend
build_frontend() {
    echo -e "${BLUE}Building frontend...${NC}"
    cd "${PROJECT_ROOT}/apps/web"
    pnpm build
    echo -e "${GREEN}✓ Frontend built successfully${NC}"
    echo ""
}

# Start all services with production frontend
start_all() {
    get_worktree_ports
    print_banner

    ensure_redis
    update_web_env
    build_frontend

    echo -e "${BLUE}Starting services...${NC}"
    echo ""

    cd "$PROJECT_ROOT"

    export API_PORT WEB_PORT

    pnpm exec concurrently \
        -n "API,WEB,CELERY" \
        -c "blue,green,yellow" \
        "cd apps/api && uv run uvicorn main:app --reload --host 0.0.0.0 --port ${API_PORT}" \
        "cd apps/web && PORT=${WEB_PORT} pnpm start" \
        "cd apps/api && uv run celery -A app.core.celery_app worker --loglevel=info --queues=notifications,classification"
}

# Start without Celery
start_no_celery() {
    get_worktree_ports
    print_banner

    ensure_redis
    update_web_env
    build_frontend

    echo -e "${BLUE}Starting API and Web (no Celery)...${NC}"
    echo ""

    cd "$PROJECT_ROOT"

    pnpm exec concurrently \
        -n "API,WEB" \
        -c "blue,green" \
        "cd apps/api && uv run uvicorn main:app --reload --host 0.0.0.0 --port ${API_PORT}" \
        "cd apps/web && PORT=${WEB_PORT} pnpm start"
}

# Start Web only (production build)
start_web() {
    get_worktree_ports
    print_banner
    update_web_env
    build_frontend

    echo -e "${BLUE}Starting Web on port ${WEB_PORT} (production mode)...${NC}"
    cd "${PROJECT_ROOT}/apps/web"
    PORT="${WEB_PORT}" pnpm start
}

# Usage
usage() {
    echo "SINAG Production-like Test Server"
    echo ""
    echo "Usage: $0 [command]"
    echo ""
    echo "This script builds the frontend first, then runs it in production mode"
    echo "for faster performance during testing."
    echo ""
    echo "Commands:"
    echo "  all, start    Build & start all services (API, Web, Celery)"
    echo "  no-celery     Build & start API and Web without Celery"
    echo "  web           Build & start Web only (production mode)"
    echo "  help          Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0              # Build and start all services"
    echo "  $0 no-celery    # Build and start without Celery"
    echo ""
}

# Main command handler
main() {
    local cmd="${1:-all}"

    case "$cmd" in
        all|start|"")
            start_all
            ;;
        no-celery|nc)
            start_no_celery
            ;;
        web)
            start_web
            ;;
        -h|--help|help)
            usage
            ;;
        *)
            echo -e "${RED}Unknown command: $cmd${NC}"
            echo ""
            usage
            exit 1
            ;;
    esac
}

main "$@"
