"""initial_schema

Revision ID: 0ddebee1b7ac
Revises:
Create Date: 2025-12-01 00:58:58.995887

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ddebee1b7ac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_cycles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("phase1_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rework_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("phase2_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calibration_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assessment_cycles_id"), "assessment_cycles", ["id"], unique=False)
    op.create_index(
        "ix_assessment_cycles_is_active",
        "assessment_cycles",
        ["is_active"],
        unique=False,
    )
    op.create_index(op.f("ix_assessment_cycles_year"), "assessment_cycles", ["year"], unique=False)
    op.create_index(
        "ix_assessment_cycles_year_desc",
        "assessment_cycles",
        [sa.literal_column("year DESC")],
        unique=False,
    )
    op.create_index(
        "uq_assessment_cycles_single_active",
        "assessment_cycles",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_table(
        "barangays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_barangays_id"), "barangays", ["id"], unique=False)
    op.create_index(op.f("ix_barangays_name"), "barangays", ["name"], unique=True)
    op.create_table(
        "governance_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column(
            "area_type",
            sa.Enum("CORE", "ESSENTIAL", name="area_type_enum", create_constraint=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_governance_areas_code"), "governance_areas", ["code"], unique=False)
    op.create_index(op.f("ix_governance_areas_id"), "governance_areas", ["id"], unique=False)
    op.create_table(
        "bbis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("mapping_rules", sa.JSON(), nullable=True),
        sa.Column("governance_area_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["governance_area_id"],
            ["governance_areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bbis_governance_area_id"), "bbis", ["governance_area_id"], unique=False
    )
    op.create_index(op.f("ix_bbis_id"), "bbis", ["id"], unique=False)
    op.create_table(
        "indicators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_auto_calculable", sa.Boolean(), nullable=False),
        sa.Column("is_profiling_only", sa.Boolean(), nullable=False),
        sa.Column("form_schema", sa.JSON(), nullable=True),
        sa.Column("calculation_schema", sa.JSON(), nullable=True),
        sa.Column("remark_schema", sa.JSON(), nullable=True),
        sa.Column("technical_notes_text", sa.String(), nullable=True),
        sa.Column("governance_area_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("indicator_code", sa.String(length=50), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("selection_mode", sa.String(length=20), nullable=True),
        sa.Column("mov_checklist_items", sa.JSON(), nullable=True),
        sa.Column(
            "validation_rule",
            sa.String(length=50),
            server_default="ALL_ITEMS_REQUIRED",
            nullable=False,
        ),
        sa.Column("is_bbi", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("effective_date", sa.DateTime(), nullable=True),
        sa.Column("retired_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["governance_area_id"],
            ["governance_areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["indicators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_indicators_id"), "indicators", ["id"], unique=False)
    op.create_index(
        op.f("ix_indicators_indicator_code"),
        "indicators",
        ["indicator_code"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "MLGOO_DILG",
                "ASSESSOR",
                "VALIDATOR",
                "BLGU_USER",
                "KATUPARAN_CENTER_USER",
                name="user_role_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("validator_area_id", sa.SmallInteger(), nullable=True),
        sa.Column("barangay_id", sa.Integer(), nullable=True),
        sa.Column(
            "preferred_language",
            sa.String(length=3),
            nullable=False,
            comment="Preferred language for AI summaries: ceb (Bisaya), fil (Tagalog), en (English)",
        ),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["barangay_id"],
            ["barangays.id"],
        ),
        sa.ForeignKeyConstraint(
            ["validator_area_id"],
            ["governance_areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "IN_REVIEW",
                "REWORK",
                "AWAITING_FINAL_VALIDATION",
                "AWAITING_MLGOO_APPROVAL",
                "COMPLETED",
                "SUBMITTED_FOR_REVIEW",
                "VALIDATED",
                "NEEDS_REWORK",
                name="assessment_status_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rework_count", sa.Integer(), nullable=False),
        sa.Column("rework_requested_at", sa.DateTime(), nullable=True),
        sa.Column("rework_requested_by", sa.Integer(), nullable=True),
        sa.Column("rework_comments", sa.Text(), nullable=True),
        sa.Column("rework_summary", sa.JSON(), nullable=True),
        sa.Column("is_calibration_rework", sa.Boolean(), nullable=False),
        sa.Column("calibration_validator_id", sa.Integer(), nullable=True),
        sa.Column("calibration_requested_at", sa.DateTime(), nullable=True),
        sa.Column("calibration_count", sa.Integer(), nullable=False),
        sa.Column("calibrated_area_ids", sa.JSON(), nullable=True),
        sa.Column("calibration_summary", sa.JSON(), nullable=True),
        sa.Column("pending_calibrations", sa.JSON(), nullable=True),
        sa.Column("calibration_summaries_by_area", sa.JSON(), nullable=True),
        sa.Column("mlgoo_approved_by", sa.Integer(), nullable=True),
        sa.Column("mlgoo_approved_at", sa.DateTime(), nullable=True),
        sa.Column("is_mlgoo_recalibration", sa.Boolean(), nullable=False),
        sa.Column("mlgoo_recalibration_requested_by", sa.Integer(), nullable=True),
        sa.Column("mlgoo_recalibration_requested_at", sa.DateTime(), nullable=True),
        sa.Column("mlgoo_recalibration_count", sa.Integer(), nullable=False),
        sa.Column("mlgoo_recalibration_indicator_ids", sa.JSON(), nullable=True),
        sa.Column("mlgoo_recalibration_comments", sa.Text(), nullable=True),
        sa.Column("grace_period_expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_locked_for_deadline", sa.Boolean(), nullable=False),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column(
            "final_compliance_status",
            sa.Enum(
                "PASSED",
                "FAILED",
                name="compliance_status_enum",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("area_results", sa.JSON(), nullable=True),
        sa.Column("ai_recommendations", sa.JSON(), nullable=True),
        sa.Column("blgu_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["blgu_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["calibration_validator_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["mlgoo_approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["mlgoo_recalibration_requested_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rework_requested_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assessments_id"), "assessments", ["id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_created_at_desc",
        "audit_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(
        "ix_audit_logs_entity_lookup",
        "audit_logs",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "checklist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("indicator_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("item_type", sa.String(length=30), server_default="checkbox", nullable=False),
        sa.Column("group_name", sa.String(length=100), nullable=True),
        sa.Column("mov_description", sa.String(), nullable=True),
        sa.Column("required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "requires_document_count",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("option_group", sa.String(length=50), nullable=True),
        sa.Column("field_notes", sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["indicator_id"], ["indicators.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("indicator_id", "item_id", name="uq_indicator_item_id"),
    )
    op.create_index(op.f("ix_checklist_items_id"), "checklist_items", ["id"], unique=False)
    op.create_index(
        op.f("ix_checklist_items_indicator_id"),
        "checklist_items",
        ["indicator_id"],
        unique=False,
    )
    op.create_table(
        "deadline_overrides",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("barangay_id", sa.Integer(), nullable=False),
        sa.Column("indicator_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("original_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("new_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["barangay_id"],
            ["barangays.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["assessment_cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deadline_overrides_barangay_id"),
        "deadline_overrides",
        ["barangay_id"],
        unique=False,
    )
    op.create_index(
        "ix_deadline_overrides_barangay_indicator",
        "deadline_overrides",
        ["barangay_id", "indicator_id"],
        unique=False,
    )
    op.create_index(
        "ix_deadline_overrides_created_at_desc",
        "deadline_overrides",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadline_overrides_created_by"),
        "deadline_overrides",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        "ix_deadline_overrides_cycle_barangay",
        "deadline_overrides",
        ["cycle_id", "barangay_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadline_overrides_cycle_id"),
        "deadline_overrides",
        ["cycle_id"],
        unique=False,
    )
    op.create_index(op.f("ix_deadline_overrides_id"), "deadline_overrides", ["id"], unique=False)
    op.create_index(
        op.f("ix_deadline_overrides_indicator_id"),
        "deadline_overrides",
        ["indicator_id"],
        unique=False,
    )
    op.create_table(
        "indicators_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("indicator_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_auto_calculable", sa.Boolean(), nullable=False),
        sa.Column("is_profiling_only", sa.Boolean(), nullable=False),
        sa.Column("form_schema", sa.JSON(), nullable=True),
        sa.Column("calculation_schema", sa.JSON(), nullable=True),
        sa.Column("remark_schema", sa.JSON(), nullable=True),
        sa.Column("technical_notes_text", sa.String(), nullable=True),
        sa.Column("indicator_code", sa.String(length=50), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("selection_mode", sa.String(length=20), nullable=True),
        sa.Column("mov_checklist_items", sa.JSON(), nullable=True),
        sa.Column("governance_area_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=False),
        sa.Column("archived_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["archived_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("indicator_id", "version", name="uq_indicator_version"),
    )
    op.create_index(op.f("ix_indicators_history_id"), "indicators_history", ["id"], unique=False)
    op.create_index(
        op.f("ix_indicators_history_indicator_id"),
        "indicators_history",
        ["indicator_id"],
        unique=False,
    )
    op.create_table(
        "assessment_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("response_data", sa.JSON(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("requires_rework", sa.Boolean(), nullable=False),
        sa.Column(
            "validation_status",
            sa.Enum(
                "PASS",
                "FAIL",
                "CONDITIONAL",
                name="validation_status_enum",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("generated_remark", sa.Text(), nullable=True),
        sa.Column("assessor_remarks", sa.Text(), nullable=True),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("indicator_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_responses_id"), "assessment_responses", ["id"], unique=False
    )
    op.create_table(
        "bbi_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "HIGHLY_FUNCTIONAL",
                "MODERATELY_FUNCTIONAL",
                "LOW_FUNCTIONAL",
                "FUNCTIONAL",
                "NON_FUNCTIONAL",
                name="bbi_status_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "compliance_percentage",
            sa.Float(),
            nullable=True,
            comment="Compliance rate 0-100%",
        ),
        sa.Column(
            "compliance_rating",
            sa.String(length=30),
            nullable=True,
            comment="3-tier rating: HIGHLY_FUNCTIONAL, MODERATELY_FUNCTIONAL, LOW_FUNCTIONAL",
        ),
        sa.Column(
            "sub_indicators_passed",
            sa.Integer(),
            nullable=True,
            comment="Number of sub-indicators that passed",
        ),
        sa.Column(
            "sub_indicators_total",
            sa.Integer(),
            nullable=True,
            comment="Total number of sub-indicators evaluated",
        ),
        sa.Column(
            "sub_indicator_results",
            sa.JSON(),
            nullable=True,
            comment="Detailed pass/fail results for each sub-indicator",
        ),
        sa.Column("calculation_details", sa.JSON(), nullable=True),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("bbi_id", sa.Integer(), nullable=False),
        sa.Column("calculation_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bbi_id"],
            ["bbis.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bbi_results_assessment_id"),
        "bbi_results",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(op.f("ix_bbi_results_bbi_id"), "bbi_results", ["bbi_id"], unique=False)
    op.create_index(op.f("ix_bbi_results_id"), "bbi_results", ["id"], unique=False)
    op.create_table(
        "mov_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("indicator_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.String(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["indicator_id"], ["indicators.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mov_files_assessment_id"), "mov_files", ["assessment_id"], unique=False
    )
    op.create_index(op.f("ix_mov_files_deleted_at"), "mov_files", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_mov_files_id"), "mov_files", ["id"], unique=False)
    op.create_index(op.f("ix_mov_files_indicator_id"), "mov_files", ["indicator_id"], unique=False)
    op.create_index(op.f("ix_mov_files_uploaded_by"), "mov_files", ["uploaded_by"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "NEW_SUBMISSION",
                "REWORK_REQUESTED",
                "REWORK_RESUBMITTED",
                "READY_FOR_VALIDATION",
                "CALIBRATION_REQUESTED",
                "CALIBRATION_RESUBMITTED",
                "VALIDATION_COMPLETED",
                "READY_FOR_MLGOO_APPROVAL",
                "MLGOO_RECALIBRATION_REQUESTED",
                "ASSESSMENT_APPROVED",
                "DEADLINE_EXPIRED_LOCKED",
                "GRACE_PERIOD_WARNING",
                name="notification_type_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=True),
        sa.Column("governance_area_id", sa.Integer(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_sent", sa.Boolean(), nullable=False),
        sa.Column("email_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["governance_area_id"], ["governance_areas.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_recipient_id"),
        "notifications",
        ["recipient_id"],
        unique=False,
    )
    op.create_table(
        "feedback_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("comment_type", sa.String(), nullable=False),
        sa.Column("is_internal_note", sa.Boolean(), nullable=False),
        sa.Column("response_id", sa.Integer(), nullable=False),
        sa.Column("assessor_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["assessment_responses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_comments_id"), "feedback_comments", ["id"], unique=False)
    op.create_table(
        "mov_annotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mov_file_id", sa.Integer(), nullable=False),
        sa.Column("assessor_id", sa.Integer(), nullable=False),
        sa.Column("annotation_type", sa.String(length=20), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("rect", sa.JSON(), nullable=False),
        sa.Column("rects", sa.JSON(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["assessor_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mov_file_id"], ["mov_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mov_annotations_assessor_id"),
        "mov_annotations",
        ["assessor_id"],
        unique=False,
    )
    op.create_index(op.f("ix_mov_annotations_id"), "mov_annotations", ["id"], unique=False)
    op.create_index(
        op.f("ix_mov_annotations_mov_file_id"),
        "mov_annotations",
        ["mov_file_id"],
        unique=False,
    )
    op.create_table(
        "movs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "UPLOADED",
                "DELETED",
                name="mov_status_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("response_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["assessment_responses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movs_id"), "movs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movs_id"), table_name="movs")
    op.drop_table("movs")
    op.drop_index(op.f("ix_mov_annotations_mov_file_id"), table_name="mov_annotations")
    op.drop_index(op.f("ix_mov_annotations_id"), table_name="mov_annotations")
    op.drop_index(op.f("ix_mov_annotations_assessor_id"), table_name="mov_annotations")
    op.drop_table("mov_annotations")
    op.drop_index(op.f("ix_feedback_comments_id"), table_name="feedback_comments")
    op.drop_table("feedback_comments")
    op.drop_index(op.f("ix_notifications_recipient_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_notification_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_mov_files_uploaded_by"), table_name="mov_files")
    op.drop_index(op.f("ix_mov_files_indicator_id"), table_name="mov_files")
    op.drop_index(op.f("ix_mov_files_id"), table_name="mov_files")
    op.drop_index(op.f("ix_mov_files_deleted_at"), table_name="mov_files")
    op.drop_index(op.f("ix_mov_files_assessment_id"), table_name="mov_files")
    op.drop_table("mov_files")
    op.drop_index(op.f("ix_bbi_results_id"), table_name="bbi_results")
    op.drop_index(op.f("ix_bbi_results_bbi_id"), table_name="bbi_results")
    op.drop_index(op.f("ix_bbi_results_assessment_id"), table_name="bbi_results")
    op.drop_table("bbi_results")
    op.drop_index(op.f("ix_assessment_responses_id"), table_name="assessment_responses")
    op.drop_table("assessment_responses")
    op.drop_index(op.f("ix_indicators_history_indicator_id"), table_name="indicators_history")
    op.drop_index(op.f("ix_indicators_history_id"), table_name="indicators_history")
    op.drop_table("indicators_history")
    op.drop_index(op.f("ix_deadline_overrides_indicator_id"), table_name="deadline_overrides")
    op.drop_index(op.f("ix_deadline_overrides_id"), table_name="deadline_overrides")
    op.drop_index(op.f("ix_deadline_overrides_cycle_id"), table_name="deadline_overrides")
    op.drop_index("ix_deadline_overrides_cycle_barangay", table_name="deadline_overrides")
    op.drop_index(op.f("ix_deadline_overrides_created_by"), table_name="deadline_overrides")
    op.drop_index("ix_deadline_overrides_created_at_desc", table_name="deadline_overrides")
    op.drop_index("ix_deadline_overrides_barangay_indicator", table_name="deadline_overrides")
    op.drop_index(op.f("ix_deadline_overrides_barangay_id"), table_name="deadline_overrides")
    op.drop_table("deadline_overrides")
    op.drop_index(op.f("ix_checklist_items_indicator_id"), table_name="checklist_items")
    op.drop_index(op.f("ix_checklist_items_id"), table_name="checklist_items")
    op.drop_table("checklist_items")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity_lookup", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at_desc", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_assessments_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_indicators_indicator_code"), table_name="indicators")
    op.drop_index(op.f("ix_indicators_id"), table_name="indicators")
    op.drop_table("indicators")
    op.drop_index(op.f("ix_bbis_id"), table_name="bbis")
    op.drop_index(op.f("ix_bbis_governance_area_id"), table_name="bbis")
    op.drop_table("bbis")
    op.drop_index(op.f("ix_governance_areas_id"), table_name="governance_areas")
    op.drop_index(op.f("ix_governance_areas_code"), table_name="governance_areas")
    op.drop_table("governance_areas")
    op.drop_index(op.f("ix_barangays_name"), table_name="barangays")
    op.drop_index(op.f("ix_barangays_id"), table_name="barangays")
    op.drop_table("barangays")
    op.drop_index(
        "uq_assessment_cycles_single_active",
        table_name="assessment_cycles",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index("ix_assessment_cycles_year_desc", table_name="assessment_cycles")
    op.drop_index(op.f("ix_assessment_cycles_year"), table_name="assessment_cycles")
    op.drop_index("ix_assessment_cycles_is_active", table_name="assessment_cycles")
    op.drop_index(op.f("ix_assessment_cycles_id"), table_name="assessment_cycles")
    op.drop_table("assessment_cycles")
    # ### end Alembic commands ###
